### ISSUE TITLE
Delegation to a retiring pool

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/fm-ledger-rules#278]
Hello! Just to clarify. Formula 5 in figure 16 here explains the delegation certificate processing, but it does not mention the `retiring` state from figure 17. Is it right that there's no special case when users try to delegate to a pool which is already in the retiring state, and generally: as long as pool **exists** - 
it is ok to delegate to it?

https://github.com/input-output-hk/fm-ledger-rules/blob/ed65f60b5270e545a3f749f8be29cba3c864471c/latex/delegation.tex#L387-L417

![image](https://user-images.githubusercontent.com/5585355/53637327-e2f1b200-3c33-11e9-9050-be57f0c449f4.png)

![image](https://user-images.githubusercontent.com/5585355/53637363-01f04400-3c34-11e9-8438-a8678f12b2f4.png)

Thank you!

**Comment by JaredCorduan** [comment]
Yes, that's correct.  If the pool does end up retiring, then the delegation is removed from the `delegations` mapping, but we don't prevent a stake holder from delegating to a pool that is retiring. We do not in fact do any checks on the pool being delegated to.  We've adopted the mantra of not disallowing things for which there is no strong reason against.

**Comment by vantuz-subhuman** [comment]
Thank you, @JaredCorduan! Makes sense, especially since technically pools may change their mind eventually )
