### ISSUE TITLE
Add aliased links to hydra built PDF's to the readme 

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/fm-ledger-rules#301]
Hydra builds our documents, so we should:

- [ ] Make sure all latex files that are compiled should be compiled by hydra.
- [ ] Make sure that the aliased links to the latest built artifacts are mentioned in the README.

**Comment by vantuz-subhuman** [comment]
![image](https://user-images.githubusercontent.com/5585355/54031694-899ffa80-41c0-11e9-82f0-82c80bb02cb8.png)
