### ISSUE TITLE
Staking Key Delegation Certificate - Nonce?

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/fm-ledger-rules#322]
Hello! Formula 5 in figure 16 in the formal spec explains how DCert<sub>delegate</sub> is processed, and it does not include any **ordering** condition, e.g. - nonce.

https://github.com/input-output-hk/fm-ledger-rules/blob/b336184ad5319feaef723d0ec57bb4b2a32b78a5/latex/delegation.tex#L387-L417

![image](https://user-images.githubusercontent.com/5585355/54230033-9dc45e80-4516-11e9-8293-11579e1e23b2.png)

In my understanding, staking-key certificates don't suffer from ordering, because you only can delete a key that already exists and that's all. But delegation certificates just replace one another, which means that if I post certificate delegating to pool A, and then 10 slots later I post new certificate delegating to pool B - the chain might get reordered and my certificates can potentially be included in another order (if used UTxOs are independent, of course). And the same comes for pool create/update and retire certificates, cuz if I post a retirement certificate and then post an update certificate, and then after chain reorder they are switched in order - the result if pretty much different.

Just to clarify - is there a solution to ensure/force certificate ordering that I just missed?

Thank you!

**Comment by JaredCorduan** [comment]
You are correct, as it stands right now, if the two delegation certs consume different inputs then there is no guarantee on the ordering. A wallet could create and consume zero valued outputs to ensure an ordering, though. Another possibility for forcing an ordering would be to set a relatively short time-to-live on the transactions, and not resend the second transaction until after the expiration of the first one.

**Comment by vantuz-subhuman** [comment]
Interesting 🤔Although TTL includes only the maximum slot to be included, right? Which means that if I issue a cert A with TTL up to slot 100 and then after slot 100 and then I issue cert B with TTL up to slot 200, and after this if last 300 blocks are rolled back - both txs with certs are valid to be included in any order, cuz their TTLs will not be validated =\ Cuz initially cert B did not exist until cert A was included, but because of nothing at stake fork potentially can be constructed at any time.

Enforcing direct ordering with depending 0-UTxOs seems to be the best option. Wonder if it might be made a part of the protocol 🤔Or if there's any reasoning for not using explicit ordering with nonces.

Thank you, @JaredCorduan!

**Comment by JaredCorduan** [comment]
Yep, that sounds right regarding the TTL.  But, we do plan to make the TTL into a range pretty soon!  Having a range does wonderful things for the [extended UTxO](https://github.com/input-output-hk/plutus/blob/master/docs/extended-utxo/README.md) model!  I agree that as things are written now, the 0-valued UTxO is the better solution.

I will think more about the nonces on these certs! And I'll also raise the issue with the others on my team. Off the top of my head it seems reasonable to add them...

as always, thank you for the great questions @vantuz-subhuman !

**Comment by vantuz-subhuman** [comment]
Also big kudos to @ppershing for great questions! :D
