### ISSUE TITLE
"pool operator key" and "stake-key" historical uniqueness

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/fm-ledger-rules#339]
Hello! Just a lil question about pool `cwitness` which is defined as "pool operator hashkey":

https://github.com/input-output-hk/fm-ledger-rules/blob/b336184ad5319feaef723d0ec57bb4b2a32b78a5/latex/delegation.tex#L80-L81

![image](https://user-images.githubusercontent.com/5585355/54481656-894ed180-4848-11e9-8c71-cabec4db3c5b.png)

Spec does not in any way define what "pool operator key" is, and how is it produced. The question is - am I getting it right that from the spec point, it is totally ok to have a new pool registered for any key for which some other pool already existed and was retired and removed, right?

The same question is for stake-keys - from spec point, it is totally ok to have a stake-key registered with `cwitness` that previously already was registered and got deleted, right?

Thank you!

**Comment by JaredCorduan** [comment]
That's exactly right.  In general, we've avoided any data structure that can only increase with time, such as an ever-growing list of retired keys.  Note that if a pool does retire, it looses all the stake delegated to it.

**Comment by vantuz-subhuman** [comment]
Thank you, Jared! That explains it! )
